### ISSUE TITLE
Imagen repetida

### ISSUE THREAD

**Issue by Sasha823** [Criptext/MonkeyChat-Web#10]
Empecé a testear con una amiga y al enviarle la imagen, ella abrió la imagen en web y no se cierra cuando haces click afuera solo se cierra si le hace click a la x.  Probando esto, lo que pasó es que al querer enviarle otras imágenes desde el archivo me seguía poniendo la primera imagen que había escogido, sin importar cuantas veces lo intentara...

**Comment by GianniCarlo** [comment]
Closing old issues that were before our complete migration to React. Please open a new issue if this still occurs in the new web chat
