### ISSUE TITLE
Monkey error en las fechas

### ISSUE THREAD

**Issue by Sasha823** [Criptext/MonkeyChat-Web#16]
@GianniCarlo Cuando se genera un link  para un private chat y el receptor lo abre en web, el emisor recibe los mensajes con fecha de 31/12/69, esto se mantiene mientras se esté en conversación, una vez que el emisor salga y esté en la lista de chats la fecha se pone bien, pero al entrar el error se repite.

**Comment by GianniCarlo** [comment]
@erikaperugachi are we still having this issue?

**Comment by GianniCarlo** [comment]
Closing old issues that were before our complete migration to React. Please open a new issue if this still occurs in the new web chat
